name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -o redis-cli-dashboard .

      - name: Test build
        run: ./redis-cli-dashboard -help

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o redis-cli-dashboard-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -o redis-cli-dashboard-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o redis-cli-dashboard-darwin-arm64 .
          GOOS=windows GOARCH=amd64 go build -o redis-cli-dashboard-windows-amd64.exe .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: redis-cli-dashboard-binaries
          path: |
            redis-cli-dashboard-linux-amd64
            redis-cli-dashboard-darwin-amd64
            redis-cli-dashboard-darwin-arm64
            redis-cli-dashboard-windows-amd64.exe
